
  create table "public"."note_tags" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid not null,
    "note_id" bigint not null
      );


alter table "public"."note_tags" enable row level security;


  create table "public"."notes" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "title" text not null,
    "body" text,
    "user_id" uuid not null
      );


alter table "public"."notes" enable row level security;


  create table "public"."tags" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "user_id" uuid not null
      );


alter table "public"."tags" enable row level security;

CREATE UNIQUE INDEX note_tags_pkey ON public.note_tags USING btree (id);

CREATE UNIQUE INDEX notes_pkey ON public.notes USING btree (id);

CREATE UNIQUE INDEX tags_pkey ON public.tags USING btree (id);

alter table "public"."note_tags" add constraint "note_tags_pkey" PRIMARY KEY using index "note_tags_pkey";

alter table "public"."notes" add constraint "notes_pkey" PRIMARY KEY using index "notes_pkey";

alter table "public"."tags" add constraint "tags_pkey" PRIMARY KEY using index "tags_pkey";

alter table "public"."note_tags" add constraint "note_tags_note_id_fkey" FOREIGN KEY (note_id) REFERENCES public.notes(id) not valid;

alter table "public"."note_tags" validate constraint "note_tags_note_id_fkey";

alter table "public"."note_tags" add constraint "note_tags_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."note_tags" validate constraint "note_tags_user_id_fkey";

alter table "public"."notes" add constraint "notes_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."notes" validate constraint "notes_user_id_fkey";

alter table "public"."tags" add constraint "tags_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."tags" validate constraint "tags_user_id_fkey";

grant delete on table "public"."note_tags" to "anon";

grant insert on table "public"."note_tags" to "anon";

grant references on table "public"."note_tags" to "anon";

grant select on table "public"."note_tags" to "anon";

grant trigger on table "public"."note_tags" to "anon";

grant truncate on table "public"."note_tags" to "anon";

grant update on table "public"."note_tags" to "anon";

grant delete on table "public"."note_tags" to "authenticated";

grant insert on table "public"."note_tags" to "authenticated";

grant references on table "public"."note_tags" to "authenticated";

grant select on table "public"."note_tags" to "authenticated";

grant trigger on table "public"."note_tags" to "authenticated";

grant truncate on table "public"."note_tags" to "authenticated";

grant update on table "public"."note_tags" to "authenticated";

grant delete on table "public"."note_tags" to "service_role";

grant insert on table "public"."note_tags" to "service_role";

grant references on table "public"."note_tags" to "service_role";

grant select on table "public"."note_tags" to "service_role";

grant trigger on table "public"."note_tags" to "service_role";

grant truncate on table "public"."note_tags" to "service_role";

grant update on table "public"."note_tags" to "service_role";

grant delete on table "public"."notes" to "anon";

grant insert on table "public"."notes" to "anon";

grant references on table "public"."notes" to "anon";

grant select on table "public"."notes" to "anon";

grant trigger on table "public"."notes" to "anon";

grant truncate on table "public"."notes" to "anon";

grant update on table "public"."notes" to "anon";

grant delete on table "public"."notes" to "authenticated";

grant insert on table "public"."notes" to "authenticated";

grant references on table "public"."notes" to "authenticated";

grant select on table "public"."notes" to "authenticated";

grant trigger on table "public"."notes" to "authenticated";

grant truncate on table "public"."notes" to "authenticated";

grant update on table "public"."notes" to "authenticated";

grant delete on table "public"."notes" to "service_role";

grant insert on table "public"."notes" to "service_role";

grant references on table "public"."notes" to "service_role";

grant select on table "public"."notes" to "service_role";

grant trigger on table "public"."notes" to "service_role";

grant truncate on table "public"."notes" to "service_role";

grant update on table "public"."notes" to "service_role";

grant delete on table "public"."tags" to "anon";

grant insert on table "public"."tags" to "anon";

grant references on table "public"."tags" to "anon";

grant select on table "public"."tags" to "anon";

grant trigger on table "public"."tags" to "anon";

grant truncate on table "public"."tags" to "anon";

grant update on table "public"."tags" to "anon";

grant delete on table "public"."tags" to "authenticated";

grant insert on table "public"."tags" to "authenticated";

grant references on table "public"."tags" to "authenticated";

grant select on table "public"."tags" to "authenticated";

grant trigger on table "public"."tags" to "authenticated";

grant truncate on table "public"."tags" to "authenticated";

grant update on table "public"."tags" to "authenticated";

grant delete on table "public"."tags" to "service_role";

grant insert on table "public"."tags" to "service_role";

grant references on table "public"."tags" to "service_role";

grant select on table "public"."tags" to "service_role";

grant trigger on table "public"."tags" to "service_role";

grant truncate on table "public"."tags" to "service_role";

grant update on table "public"."tags" to "service_role";


